
server:
  port: 8080
  servlet:
    context-path: /custom

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.34.10:3306/development?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: developer
    password: Dev@123456
    type: com.alibaba.druid.pool.DruidDataSource
  activiti:
    check-process-definitions: true #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    history-level: full #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    process-definition-location-prefix: classpath:/processes #流程定义文件存放目录
    #process-definition-location-suffixes: #流程文件格式
    #  - **.bpmn20.xml
    #  - **.bpmn

  jpa:
    database: mysql
    show-sql: true
mybatis:
  mapper-locations: classpath:mybatis/*.xml  # 注意:一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.customprocess.api.model  # 注意:对应实体类的路径
  configuration:
    map-underscore-to-camel-case: true # 数据库字段下划线自动转驼峰
